Linux64: v2.3

diff --git a/.scripts/repack_img b/.scripts/repack_img
--- a/.scripts/repack_img
+++ b/.scripts/repack_img
@@ -3,7 +3,7 @@ e="\x1b[";c=$e"00m";y=$e"93;01m";cy=$e"96;01m";bb=$e"96;44;01m";r=$e"1;91m";g=$e
 ##########################################################
 #                                                        #
 #           Carliv Image Kitchen for Android             #
-#     boot+recovery images copyright-2020 carliv.eu      #
+#       boot & recovery images (c)-2021 carliv.eu        #
 #    including support for MTK powered phones images     #
 #                                                        #
 ##########################################################
@@ -20,8 +20,8 @@ clear;
 echo -e "$bb
 *****************************************************
 *                                                   *
-*      Carliv Image Kitchen for Android v2.1        *
-*  boot+recovery images copyright(c)2020 carliv.eu  *
+*        Carliv Image Kitchen for Android v2.3      *
+*      boot & recovery images (c)2021 carliv.eu     *
 *  including support for MTK powered phones images  *
 *                 LINUX x64 version                 *
 *                                                   *
@@ -36,6 +36,10 @@ if [ ! "$1" ];
 	abort;
 	exit 1;
 fi;
+if [ ! -d "output" ];
+	then
+	mkdir -p "output";
+fi;
 ###########################################################
 imgfolder=$(basename "$1");
 echo -e "Processing the$y $imgfolder$c folder.";
@@ -44,16 +48,17 @@ cd "$imgfolder";
 ###########################################################
 echo "Repacking the image....";
 echo " ";
-getfile=$(find . -name "*.img-kernel");
-myname="${getfile%.*}";
-kernel="$myname".img-kernel;
-if [[ -z "$kernel" ]];
+if [ ! -e "vendor_boot" ];
 	then
-	echo -e "$r The$c$y kernel$c$r file is missing. Check your folder!. ERROR!$c";
-	abort;
-	exit 1;
+	if [ ! -e "kernel" ];
+		then
+		echo -e "$r The$c$y kernel$c$r file is missing. Check your folder!. ERROR!$c";
+		abort;
+		exit 1;
+		else
+		kernel=kernel;
+	fi;
 fi;
-echo -e "The kernel is:$y $kernel$c";
 echo " ";
 echo -e "Getting the$y ramdisk$c compression....";
 echo " ";
@@ -63,14 +68,20 @@ if [ ! -d "ramdisk" ];
 	abort;
 	exit 1;
 fi;
-compress=$(cat "$myname".img-ramdisk-compress);
+if [ ! -e "ramdisk_compress" ];
+	then
+	echo -e "$r The$c$y ramdisk_compress$c$r file is missing. Check your folder!. ERROR!$c";
+	abort;
+	exit 1;
+fi;
+compress=$(cat ramdisk_compress);
 echo -e "Compression used:$y $compress$c";
 echo " ";
 ###########################################################
 if [ "$compress" == "gz" ];
 	then
-	$mkbootfs ramdisk | $minigzip -c -9 > "$myname".img-ramdisk.gz;
-	ramdisk="$myname".img-ramdisk.gz;
+	$mkbootfs ramdisk | $minigzip -c -9 > ramdisk.gz;
+	ramdisk=ramdisk.gz;
 	echo -e "The ramdisk is:$y $ramdisk$c";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -81,8 +92,8 @@ if [ "$compress" == "gz" ];
 fi;
 if [ "$compress" == "lzma" ];
 	then
-	$mkbootfs ramdisk | xz --format=lzma -1zv > "$myname".img-ramdisk.lzma;
-	ramdisk="$myname".img-ramdisk.lzma;
+	$mkbootfs ramdisk | xz --format=lzma -1zv > ramdisk.lzma;
+	ramdisk=ramdisk.lzma;
 	echo -e "The ramdisk is:$y $ramdisk$c";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -93,8 +104,8 @@ if [ "$compress" == "lzma" ];
 fi;
 if [ "$compress" == "xz" ];
 	then
-	$mkbootfs ramdisk | xz -1zv -Ccrc32 > "$myname".img-ramdisk.xz;
-	ramdisk="$myname".img-ramdisk.xz;
+	$mkbootfs ramdisk | xz -1zv -Ccrc32 > ramdisk.xz;
+	ramdisk=ramdisk.xz;
 	echo -e "The ramdisk is:$y $ramdisk$c";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -105,8 +116,8 @@ if [ "$compress" == "xz" ];
 fi;
 if [ "$compress" == "bz2" ];
 	then
-	$mkbootfs ramdisk | bzip2 -v > "$myname".img-ramdisk.bz2;
-	ramdisk="$myname".img-ramdisk.bz2;
+	$mkbootfs ramdisk | bzip2 -v > ramdisk.bz2;
+	ramdisk=ramdisk.bz2;
 	echo "The ramdisk is: $ramdisk";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -117,8 +128,8 @@ if [ "$compress" == "bz2" ];
 fi;
 if [ "$compress" == "lzo" ];
 	then
-	$mkbootfs ramdisk | lzop -v > "$myname".img-ramdisk.lzo;
-	ramdisk="$myname".img-ramdisk.lzo;
+	$mkbootfs ramdisk | lzop -v > ramdisk.lzo;
+	ramdisk=ramdisk.lzo;
 	echo "The ramdisk is: $ramdisk";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -129,8 +140,8 @@ if [ "$compress" == "lzo" ];
 fi;
 if [ "$compress" == "lz4" ];
 	then
-	$mkbootfs ramdisk | lz4 -l stdin stdout > "$myname".img-ramdisk.lz4;
-	ramdisk="$myname".img-ramdisk.lz4;
+	$mkbootfs ramdisk | lz4 -l stdin stdout > ramdisk.lz4;
+	ramdisk=ramdisk.lz4;
 	echo "The ramdisk is: $ramdisk";
 	if [ ! $? -eq "0" ]; 
 	then
@@ -144,184 +155,197 @@ echo " ";
 echo " ";
 echo "Getting the image repacking arguments....";
 echo " ";
+bkernel="";
+bramdisk="";
 bboard="";
 bbase="";
 pagesz="";
 bkoff="";
 brmoff="";
 bsecoff="";
-second="";
+bsecond="";
 btgoff="";
 bdt="";
-dtb="";
+bdtb="";
 bdtboff="";
-dtbo="";
-acpio="";
+bdtbo="";
+bacpio="";
 bosver="";
 bpaklev="";
 bhdrver="";
 bhashtp="";
-######################### BOARD ###########################
-if [[ -f "$myname".img-board ]];
+bcmdline="";
+bout="";
+bmtk="";
+######################### KERNEL ###########################
+if [ ! -e "vendor_boot" ];
 	then
-	bname=$(cat "$myname".img-board);
-	if [[ -n "$bname" ]]; then
+	if [ -e "kernel" ]; then
+		bkernel=" --kernel $kernel";
+		echo -e "The kernel is:$y kernel$c";echo " ";
+	fi;
+fi;
+######################### RAMDISK ###########################
+if [ -f "$ramdisk" ];
+	then
+	if [ ! -e "vendor_boot" ];
+		then
+		bramdisk=" --ramdisk $ramdisk";
+		else
+		bramdisk=" --vendor_ramdisk $ramdisk";
+	fi;
+	echo -e "The ramdisk is:$y $ramdisk$c";echo " ";
+fi;
+######################### BOARD ###########################
+if [ -e "board" ];
+	then
+	bname=$(cat board);
+	if [ -n "$bname" ]; then
 		bboard=" --board $bname";
 		echo -e "Board:$y             $bname$c";echo " ";
 	fi;
 fi;
 ########################## BASE ############################
-if [[ -f "$myname".img-base ]];
+if [ -e "base" ];
 	then
-	base=$(cat "$myname".img-base);
+	base=$(cat base);
 	bbase=" --base $base";
 	echo -e "Base:$y              $base$c";echo " ";
 fi;
 ######################## PAGESIZE ##########################
-if [[ -f "$myname".img-pagesize ]];
+if [ -e "pagesize" ];
 	then
-	pagesize=$(cat "$myname".img-pagesize);
+	pagesize=$(cat pagesize);
 	pagesz=" --pagesize $pagesize";
 	echo -e "Pagesize:$y          $pagesize$c";echo " ";
 fi;
 ######################## CMDLINE ###########################
-if [[ -f "$myname".img-cmdline ]];
+if [ -e "cmdline" ];
 	then
-	lcmd=$(cat "$myname".img-cmdline);
+	lcmd=$(cat cmdline);
+	if [ ! -e "vendor_boot" ];
+		then
+		bcmdline=" --cmdline ";
+		else
+		bcmdline=" --vendor_cmdline ";
+	fi;
 	echo -e "Command line:$y      $lcmd$c";echo " ";
 fi;
 ##################### KERNEL OFFSET ########################
-if [[ -f "$myname".img-kernel_offset ]];
+if [ -e "kernel_offset" ];
 	then
-	keoff=$(cat "$myname".img-kernel_offset);
+	keoff=$(cat kernel_offset);
 	bkoff=" --kernel_offset $keoff";
 	echo -e "Kernel offset:$y     $keoff$c";echo " ";
 fi;
 ##################### RAMDISK OFFSET #######################
-if [[ -f "$myname".img-ramdisk_offset ]];
+if [ -e "ramdisk_offset" ];
 	then
-	ramoff=$(cat "$myname".img-ramdisk_offset);
+	ramoff=$(cat ramdisk_offset);
 	brmoff=" --ramdisk_offset $ramoff";
 	echo -e "Ramdisk offset:$y    $ramoff$c";echo " ";
 fi;
 ###################### SECOND OFFSET ########################
-if [[ -f "$myname".img-second_offset ]];
+if [ -e "second_offset" ];
 	then
-	flsec=$(cat "$myname".img-second_offset);
+	flsec=$(cat second_offset);
 	bsecoff=" --second_offset $flsec";
 	echo -e "Second offset:$y     $flsec$c";echo " ";	
 fi;
 #################### SECOND BOOTLOADER ######################
-if [[ -f "$myname".img-second ]];
+if [ -e "second" ];
 	then
-	secboot="$myname".img-second;
-	second=" --second $secboot";
-	echo -e "Second bootloader:$y $secboot$c";echo " ";
+	bsecond=" --second second";
+	echo -e "Second bootloader:$y second$c";echo " ";
 fi;
 ###################### TAGS OFFSET ##########################
-if [[ -f "$myname".img-tags_offset ]];
+if [ -e "tags_offset" ];
 	then
-	tagoff=$(cat "$myname".img-tags_offset);
+	tagoff=$(cat tags_offset);
 	btgoff=" --tags_offset $tagoff";
 	echo -e "Tags offset:$y       $tagoff$c";echo " ";
 fi;
 ############################ DT ##############################
-if [[ -f "$myname".img-dt ]];
+if [ -e "dt" ];
 	then
-	ldtb="$myname".img-dt;
-	bdt=" --dt $ldtb";
-	echo -e "Device tree blob:$y  $ldtb$c";echo " ";
+	bdt=" --dt dt";
+	echo -e "Device tree blob:$y  dt$c";echo " ";
 fi;
 ############################ DTB #############################
-if [[ -f "$myname".img-dtb ]];
+if [ -e "dtb" ];
 	then
-	ldtbb="$myname".img-dtb;
-	dtb=" --dtb $ldtbb";
-	echo -e "Device tree blob:$y  $ldtbb$c";echo " ";
+	bdtb=" --dtb dtb";
+	echo -e "Device tree blob:$y  dtb$c";echo " ";
 fi;
 ####################### DTB OFFSET ##########################
-if [[ -f "$myname".img-dtb_offset ]];
+if [ -e "dtb_offset" ];
 	then
-	dtboff=$(cat "$myname".img-dtb_offset);
+	dtboff=$(cat dtb_offset);
 	bdtboff=" --dtb_offset $dtboff";
 	echo -e "Device tree blob offset:$y       $dtboff$c";echo " ";
 fi;
 ############################ DTBO ############################
-if [[ -f "$myname".img-dtbo ]];
+if [ -e "recovery_dtbo" ];
 	then
-	ldtbbo="$myname".img-dtbo;
-	dtbo=" --recovery_dtbo $ldtbbo";
-	echo -e "Device tree blob overlay:$y  $ldtbbo$c";echo " ";
+	bdtbo=" --recovery_dtbo recovery_dtbo";
+	echo -e "Device tree blob overlay:$y  recovery_dtbo$c";echo " ";
 fi;
 ########################### ACPIO ############################
-if [[ -f "$myname".img-acpio ]];
+if [ -e "recovery_acpio" ];
 	then
-	lacpio="$myname".img-acpio;
-	acpio=" --recovery_acpio $lacpio";
-	echo -e "Non AB ACPIO:$y  $lacpio$c";echo " ";
+	bacpio=" --recovery_acpio recovery_acpio";
+	echo -e "Non AB ACPIO:$y  recovery_acpio$c";echo " ";
 fi;
 ####################### OS VERSION ##########################
-if [[ -f "$myname".img-os_version ]];
+if [ -e "os_version" ];
 	then
-	osvers=$(cat "$myname".img-os_version);
+	osvers=$(cat os_version);
 	bosver=" --os_version $osvers";
 	echo -e "OS version:$y       $osvers$c";echo " ";
 fi;
 ######################## OS PATCH ##########################
-if [[ -f "$myname".img-os_patch_level ]];
+if [ -e "os_patch_level" ];
 	then
-	paklev=$(cat "$myname".img-os_patch_level);
+	paklev=$(cat os_patch_level);
 	bpaklev=" --os_patch_level $paklev";
 	echo -e "OS release date:$y       $paklev$c";echo " ";
 fi;
 ##################### HEADER VERSION ########################
-if [[ -f "$myname".img-header_version ]];
+if [ -e "header_version" ];
 	then
-	hdrver=$(cat "$myname".img-header_version);
+	hdrver=$(cat header_version);
 	bhdrver=" --header_version $hdrver";
 	echo -e "Boot header version:$y       $hdrver$c";echo " ";
 fi;
 ####################### HASH TYPE ##########################
-if [[ -f "$myname".img-hashtype ]];
+if [ -e "hashtype" ];
 	then
-	hashtp=$(cat "$myname".img-hashtype);
+	hashtp=$(cat hashtype);
 	bhashtp=" --hashtype $hashtp";
 	echo -e "Boot hash type:$y       $hashtp$c";echo " ";
 fi;
+####################### MTK ##########################
+if [ -e "mtk" ];
+	then
+	lmtk=$(cat mtk);
+	bmtk=" --mtk $lmtk";
+fi;
+######################## OUTPUT ###########################
+if [ ! -e "vendor_boot" ];
+	then
+	bout=" --output";
+	else
+	bout=" --vendor_boot";
+fi;
 ###########################################################
 stamp=cik-$(date +"%H%M");
-if [[ -f recovery.txt ]];
-	then
-	filetype=$(cat recovery.txt);
-elif [[ -f boot.txt ]];
-	then
-	filetype=$(cat boot.txt);
-else
-	filetype="boot";
-fi;
-newimage="$filetype"_temp.img;
-packedimg="$imgfolder"_"$stamp".img;
+newimage=cika.img;
+packedimg="$imgfolder"-"$stamp".img;
 echo " ";
 echo "Executing the repacking command...."
 echo " ";
-if [[ -f "$myname".img-mtk ]];
-	then
-	$mkbootimg --kernel $kernel --ramdisk $ramdisk$second$dtb$dtbo$acpio --cmdline "$lcmd"$bboard$bbase$pagesz$bdt$bkoff$brmoff$bsecoff$btgoff$bdtboff$bosver$bpaklev$bhdrver$bhashtp --mtk 1 -o ../output/"$newimage";
-	if [ ! $? -eq "0" ]; 
-		then
-		abort;
-		exit 1;
-	fi;
-	else
-	$mkbootimg --kernel $kernel --ramdisk $ramdisk$second$dtb$dtbo$acpio --cmdline "$lcmd"$bboard$bbase$pagesz$bdt$bkoff$brmoff$bsecoff$btgoff$bdtboff$bosver$bpaklev$bhdrver$bhashtp -o ../output/"$newimage";
-	if [ ! $? -eq "0" ]; 
-		then
-		abort;
-		exit 1;
-	fi;
-fi;
-compramdisk="$myname".img-ramdisk."$compress";
-rm -f "$compramdisk";
+$mkbootimg$bkernel$bramdisk$bsecond$bdtb$bdtbo$bacpio$bcmdline"$lcmd"$bboard$bbase$pagesz$bdt$bkoff$brmoff$bsecoff$btgoff$bdtboff$bosver$bpaklev$bhdrver$bhashtp$bmtk$bout ../output/$newimage;
+rm -f "$ramdisk";
 cd ../;
 mv -f output/"$newimage" output/"$packedimg";
 echo " ";
